
SUBDIRS = \
	libgwyddion \
	libprocess \
	libdraw \
	libgwydgets \
	libgwymodule \
	app \
	modules \
	pixmaps

DOCUMENTS = \
	COPYING.wri

## targets
all: sub-all $(DOCUMENTS)

clean: sub-clean

install: sub-install

!INCLUDE rules.msc

# FIXME:
COPYING.wri: COPYING
	copy COPYING COPYING.wri

# vim: ft=make
