'\" t
.\"     Title: gwyddion-thumbnailer
.\"    Author: Yeti
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 09/04/2009
.\"    Manual: Gwyddion
.\"    Source: gwyddion
.\"  Language: English
.\"
.TH "GWYDDION\-THUMBNAILE" "1" "09/04/2009" "gwyddion" "Gwyddion"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gwyddion-thumbnailer \- Create thumbnails of SPM data files
.SH "SYNOPSIS"
.HP \w'\fBgwyddion\-thumbnailer\fR\ 'u
\fBgwyddion\-thumbnailer\fR {\-\-version | \-\-help}
.HP \w'\fBgwyddion\-thumbnailer\fR\ 'u
\fBgwyddion\-thumbnailer\fR [\fIOPTION\fR...] {\fIMODE\fR} [\fIARGUMENT\fR...]
.SH "DESCRIPTION"
.PP
Gwyddion\-thumbnailer creates thumbnails of SPM (Scanning Probe Microscope) image files\&. Depending on the mode of operation, described below, the thumbnails are written to conform to various desktop standards so that they can be displayed in
\fBnautilus\fR(1),
\fBthunar\fR(1)
and similar file managers\&.
.PP
Gwyddion\-thumbnailer loads and renders files using
\fBgwyddion\fR(1), libraries and modules, therefore, it can create thumbnails of all file formats supported by your Gwyddion installation\&. This also means it inherits Gwyddion settings, e\&.g\&. the default false color gradient, and that it is influenced by the same environment variables as Gwyddion\&.
.SH "INFORMATIVE OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Prints a brief help and terminates\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Prints version information and terminates\&.
.RE
.SH "THUMBNAILING OPTIONS"
.PP
\fB\-\-update\fR
.RS 4
Writes the thumbnail only if it does not exist yet or does not seem to be up\-to\-date\&. By default, gwyddion\-thumbnailer overwrites existing thumbnails with fresh ones even if they seem up to date\&.
.RE
.SH "MODE"
.PP
Three thumbnailing modes are available:
\fBgnome2\fR,
\fBtms\fR
and
\fBkde4\fR; and one special mode:
\fBcheck\fR\&. They are described below\&.
.SH "GNOME 2"
.HP \w'\fBgwyddion\-thumbnailer\fR\ 'u
\fBgwyddion\-thumbnailer\fR [\fIOPTION\fR...] gnome2 \fIMAX\-SIZE\fR \fIINPUT\-FILE\fR \fIOUTPUT\-FILE\fR
.PP
In
\fBgnome2\fR
mode, gwyddion\-thumbnailer creates PNG thumbnails according to the Gnome thumbnailer specification\&. Usings the convention from this specification, it should be run
.sp
.if n \{\
.RS 4
.\}
.nf
gwyddion\-thumbnailer gnome2 %s %i %o
.fi
.if n \{\
.RE
.\}
.PP
Gwyddion installs the corresponding GConf schemas and enables thumbnailers for all file types it supports by default, so usually this should Just Work and should not need to be set up manually\&.
.PP
The thumbnails created in
\fBgnome2\fR
more are identical as in
\fBtms\fR
mode, including all the PNG auxiliary chunks (provided that the same
\fIMAX\-SIZE\fR
as in
\fBtms\fR
mode is specified, of course)\&.
.SH "TMS"
.HP \w'\fBgwyddion\-thumbnailer\fR\ 'u
\fBgwyddion\-thumbnailer\fR [\fIOPTION\fR...] tms \fIMAX\-SIZE\fR \fIINPUT\-FILE\fR
.PP
In
\fBtms\fR
mode, gwyddion\-thumbnailer creates PNG thumbnails according to the Thumbnail Managing Standard\&. Argument
\fIMAX\-SIZE\fR
must be
\fB128\fR
or
\fBnormal\fR
(both meaning 128 pixels) or
\fB256\fR
or
\fBlarge\fR
(both meaning 256 pixels)\&.
.PP
Output file name is not given as it is prescribed by the TMS\&. The thumbnail is placed to the directory for normal or large thumbnails according to given
\fIMAX\-SIZE\fR\&.
.PP
This mode can also be useful for manual batch\-creation of thumbnails\&. For instance, to create them for all
*\&.afm
files in directory
scans
and its subdirectories, you can run
.sp
.if n \{\
.RS 4
.\}
.nf
find scans \-type f \-name \'*\&.afm\' \-print0 \e\e
    | xargs \-0 \-n 1 gwyddion\-thumbnailer \-\-update tms normal
.fi
.if n \{\
.RE
.\}
.PP
And then go make yourself a coffee because this will take some time\&.
.SH "KDE 4"
.HP \w'\fBgwyddion\-thumbnailer\fR\ 'u
\fBgwyddion\-thumbnailer\fR kde4 \fIMAX\-SIZE\fR \fIINPUT\-FILE\fR
.PP
In
\fBkde4\fR
mode, gwyddion\-thumbnailer creates PNG thumbnails that are intended to be consumed by gwythumbcreator KDE module\&. The thumbnail, again identical as in the other modes, is written to the standard output\&.
.PP
Do
\fInot\fR
use this mode from the command line\&. It is documented for completness, however, the protocol between gwythumbcreator and gwyddion\-thumbnailer must be considered private and it can change any time\&.
.SH "CHECK"
.HP \w'\fBgwyddion\-thumbnailer\fR\ 'u
\fBgwyddion\-thumbnailer\fR check \fIINPUT\-FILE\fR
.PP
The
\fBcheck\fR
mode does not serve for thumbnail creation\&. Instead, gwyddion\-thumbnailer prints information about available thumbnails of
\fIINPUT\-FILE\fR
and cached failures to produce a thumbnail by individual applications, as described by the TMS\&.
.PP
If the normal\-sized thumbnail exists and is up to date, the large version does not exist and there is one cached failure from gnome\-thumbnail\-factory, the output can be for instance:
.sp
.if n \{\
.RS 4
.\}
.nf
File:   \fIINPUT\-FILE\fR
URI:    file:///home/me/Pictures/naughty/broken\-tip3/\fIINPUT\-FILE\fR
Normal: /home/me/\&.thumbnails/normal/\fIMD5\fR\&.png
        status: OK
Large:  /home/me/\&.thumbnails/large/\fIMD5\fR\&.png
        status: Thumbnail does not exist or stat() fails on it\&.
Failed: /home/me/\&.thumbnails/fail/gnome\-thumbnail\-factory/\fIMD5\fR\&.png
.fi
.if n \{\
.RE
.\}
.PP
URI is the canonical URI of the input file,
\fIMD5\fR
stands for the hex representation of MD5 sum of the URI, as described by the TMS\&. If there are no cached failures, no Failed lines are printed\&.
.PP
This function can be used to check thumbnails of any kind, not necessarily created by gwyddion or gwyddion\-thumbnailer\&. In future, it might be reported as an error if the thumbnail does not contain Gwyddion\-specific information though\&.
.SH "SEE ALSO"
.PP

\fBgwyddion\fR(1),
.SH "AUTHOR"
.PP
\fBYeti\fR
.RS 4
Author.
.RE
