#!/bin/sed -f
s/define-object Serializable/define-interface Serializable/
s/GWY_TYPE_SELECTION_GRAPH1_DAREA/GWY_TYPE_SELECTION_GRAPH_1DAREA/
s/GWY_TYPE_NL_FIT_PRESET/GWY_TYPE_NLFIT_PRESET/
s/GWY_TYPE_CD_LINE/GWY_TYPE_CDLINE/
