#!/bin/sh

app_name=gwyddion
gwyddion_app_dir=${app_name}.app
contents_dir=${gwyddion_app_dir}/Contents
bin_dir=${contents_dir}/MacOS
res_dir=${contents_dir}/Resources
gwy_modules_dir=${res_dir}/modules

rm -rf ${gwyddion_app_dir}
mkdir ${gwyddion_app_dir}
mkdir ${contents_dir}
mkdir ${bin_dir}
mkdir ${res_dir}


if [ $# -lt 1 ] ; then
   echo "Syntax: $0: prefix\n"
   echo "Example:$0 /usr/local/\n"
   exit 1
fi

prefix=$1

cp ${prefix}/bin/${app_name} ${bin_dir}/
cp -R ${prefix}/share/${app_name}/* ${res_dir}/
cp ${app_name}.icns ${res_dir}/
mkdir ${gwy_modules_dir}

cp ${prefix}/lib/${app_name}/modules/*.so ${gwy_modules_dir}/

for filename in ${prefix}/lib/${app_name}/modules/*
do

if [ -d "$filename" ]; then
directory_name=`basename ${filename}`
  	mkdir ${gwy_modules_dir}/${directory_name}
	cp ${filename}/*.so ${gwy_modules_dir}/${directory_name}/
fi
done;


cat << EOT > ${contents_dir}/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>English</string>
        <key>CFBundleExecutable</key>
        <string>gwyddion</string>
        <key>CFBundleGetInfoString</key>
        <string>gwyddion</string>
        <key>CFBundleIconFile</key>
        <string>gwyddion.icns</string>
        <key>CFBundleIdentifier</key>
        <string>com.gwyddion.gwyddion</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>0.3</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>0.3</string>
        <key>NSHumanReadableCopyright</key>
        <string></string>
        <key>LSMinimumSystemVersion</key>
        <string>10.4</string>
</dict>
</plist>
EOT
