#!/bin/bash
# @(#) $Id$
# Extract a list of all declaration (as generated by gtk-doc).  Useful for
# API comparison.
set -e

die() {
  echo "$1" 1>&2
  exit 1
}

force=
if test "x$1" = "x-f"; then
  force=force
  shift
fi

mimetype=$(file -Lbi "$1" 2>/dev/null)
test "$mimetype" == "application/x-bzip2" \
  || die "Usage: $0 GWYDDION-TARBALL.tar.bz2"

toplevel=$(tar -jtf "$1" | cut -d/ -f1 | uniq)
test $(echo $toplevel | wc -w) == 1 \
  || die "Multiple toplevels: $toplevel"
out=$toplevel.symbols
test ! -e "$out"  -o -n "$force" \
  || die "Refusing to overwrite existing $out"

tar -Ojxvf "$1" "$toplevel/devel-docs/libgwy*/libgwy*-sections.txt" >$out
