#!/bin/bash
# @(#) $Id$
# Extract a list of all declaration (as generated by gtk-doc).  Useful for
# API comparison.
set -e

die() {
  echo "$1" 1>&2
  exit 1
}

force=
if test "x$1" = "x-f"; then
  force=force
  shift
fi

mimetype=$(file -Lbi "$1" 2>/dev/null)
case "$mimetype" in
  application/x-bzip2) dec=j;;
  application/x-gzip) dec=z;;
  *) die "Usage: $0 GWYDDION-TARBALL";;
esac

toplevel=$(tar -$dec -tf "$1" | cut -d/ -f1 | uniq)
test $(echo $toplevel | wc -w) == 1 \
  || die "Multiple toplevels: $toplevel"
out=$toplevel.symbols
test ! -e "$out"  -o -n "$force" \
  || die "Refusing to overwrite existing $out"

tar -$dec -Oxvf "$1" "$toplevel/devel-docs/libgwy*/html/libgwy*.devhelp2" \
  | sed -e 's/^ *<keyword /<keyword /;t;d' \
  >$out
