#!/bin/bash
pkgname=gwyddion
logdir=$HOME/Projects/Gwyddion/buildlog
phpswroot=$HOME/PHP/software
tmplog=tmplog

source $HOME/.bashrc
source $HOME/.ssh/current-ssh-agent
cd $logdir

cat >autostuff.ignore <<':'
^/usr/share/aclocal/.*.m4:[0-9]*: warning: underquoted definition of 
^  run info '(automake)Extending aclocal'
^  or see http://sources\.redhat\.com/automake/automake.html#Extending%20aclocal
^  or see http://sources\.redhat\.com/automake/automake.html#Extending-aclocal
':'
:

cat >build_documentation.ignore <<':'
^Writing .* for [^ ]\+(.*)
^lib.*-scan\.c: In function
^lib.*-scan\.c:[0-9]*: warning: unused parameter
^lib.*-scan\.c:[0-9]*: warning: .* shadows a previous local
^lib.*-scan\.c:[0-9]*: warning: shadowed declaration is here
^Computing chunks\.\.\.
^  These can be found in [a-z]\+-unused\.txt\.
^  They should be added to [a-z]\+-sections\.txt in the appropriate place\.
':'
:

cat >make_dists.ignore <<':'
^+
^cp: cannot stat `\./html/\*\.css': No such file or directory
^make\[3\]: \[dist-hook\] Error 1 (ignored)
^libtool: install: warning: relinking `.*.la'
^libtool: install: warning: `.*\.la' has not been installed in `/usr/lib
^libtool: install: warning: remember to run `libtool --finish /usr/lib
\.\{6,\}
^[0-9]\+ blocks
':'
:

cat >gnains_index.ignore <<':'
*** gnains-mkindex-Warning: Cannot decide what to do with <.*>
*** gnains-mkindex-Warning: Duplicit key <.*>
':'
:

cat >install_to_tmp.ignore <<':'
^libtool: install: warning: relinking `.*.la'
':'
:

function printerr() {
  f=$1
  shift

  test -s $f.err || return
  cat --squeeze-blank $f.err \
  | {
    if test -s $f.ignore; then
      grep -v -f $f.ignore
    else
      cat
    fi
  } | {
    if test -n "$1"; then
      $@
    else
      cat
    fi
  } >$tmplog
  test -s $tmplog || return
  echo "=====[ $f ]====="
  cat $tmplog
}

function extract_build_documentation() {
  test -s $tmplog || echo "=====[ build_documentation ]====="
  logfile=build_documentation.log
  e='Entering directory'
  l='Leaving directory'
  grep -P "^(WARNING|ERROR)\\b.*(\\n\\s+.*)*|$e|$l|^\\d+%" \
    $logfile | grep -v -f build_documentation.ignore >$tmplog
  libs=$(grep "$e" $logfile | sed -e 's#.*/##' -e 's/.$//')
  for x in $libs; do
    echo -n "$x: "
    sed -n -e "/$e .*\\/$x'/,/$l .*\\/$x'/p" $tmplog \
      | sed -n -e '/ symbol /{s/ symbols*//g;p}'
    sed -n -e "/$e .*\\/$x'/,/$l .*\\/$x'/p" $tmplog \
      | sed -e '1d;$d;/ symbol /d'
  done
}

function coding_style_report() {
  phpdir=$phpswroot/$pkgname
  base=coding-style-byfile
  cut -d: -f1 coding-style.log  | uniq -c | sort -nr >$base.log
  head -n 20 $base.log >$phpdir/$base.txt
  printf '% 7d total' $(wc -l <coding-style.log) >>$phpdir/$base.txt

  base=coding-style-bytype
  cut -d: -f3- coding-style.log \
    | sed -e 's/: .*//' -e 's/ (col [0-9]*)//' | sort | uniq -c | sort -nr \
    >$base.log
  head -n 20 $base.log >$phpdir/$base.txt
  printf '% 7d  total' $(wc -l <coding-style.log) >>$phpdir/$base.txt
}

printerr update_tags
printerr update_version
printerr autostuff
printerr build_project
printerr build_documentation
extract_build_documentation
printerr check_coding_style
coding_style_report
printerr install_to_tmp grep -vFf build_project.err
printerr make_dists grep -vFf build_project.err
printerr release_dists
printerr gnains_index
printerr webify_api

rm *.ignore $tmplog
