# @(#) $Id$

TOP_SRCDIR = ..

!INCLUDE $(TOP_SRCDIR)\make.msc

SUBDIRS = \
	glmaterials \
	gradients

## targets
all: sub-all

clean:: sub-clean

install-iss:
	$(INSTALL) gwyddion.iss "$(DEST_DIR)"
	$(INSTALL) gwyddion-devel.iss "$(DEST_DIR)"

install: install-iss sub-install

!INCLUDE $(TOP_SRCDIR)\rules.msc

# vim: ff=dos ft=make
