
TOP_SRCDIR = ../..
MOD_TYPE = graph
MODULES = \
	read.dll

!INCLUDE $(TOP_SRCDIR)\make.msc

# NOT MOD_CFLAGS!
LIB_CFLAGS = \
	-I . -I $(TOP_SRCDIR) $(COMMON_CFLAGS) $(MOD_CRUNTIME) \
	$(GTK_CFLAGS) \
	$(GDK_PIXBUF_CFLAGS) \
	-DG_LOG_DOMAIN=\"Module\"

## targets
all: mod

mod: $(MODULES)

install: install-mod

!INCLUDE $(TOP_SRCDIR)\rules.msc

read.dll: read.obj
	$(LINK32) read.obj $(MOD_LINK) $(WIN32LIBS) $(LDFLAGS) /out:read.dll /dll /implib:read.lib


# vim: ft=make
